spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        validation-mode: none
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
    show-sql: false